import 'package:diary/domain/diary_entry.dart';

final demoEntries = <DiaryEntry>[
  DiaryEntry(
    id: 'slow-down',
    createdAt: DateTime(2026, 9, 15, 8, 40),
    updatedAt: DateTime(2026, 9, 15, 8, 40),
    title: '慢下来，生活才会发光',
    content: '早起走了一小段路。风从树叶之间穿过，像是把这几天积攒的急促，轻轻吹散了。今天不追赶什么，只想把每一个当下收好。',
    contentText: '早起走了一小段路。风从树叶之间穿过，像是把这几天积攒的急促，轻轻吹散了。今天不追赶什么，只想把每一个当下收好。',
    category: '生活',
    mood: 0.72,
    tags: ['慢生活', '散步'],
    colorValue: 0xFFDCE6D9,
    isFavorite: true,
  ),
  DiaryEntry(
    id: 'weekend',
    createdAt: DateTime(2026, 9, 13, 21, 12),
    updatedAt: DateTime(2026, 9, 13, 21, 12),
    title: '把周末留给自己',
    content: '关掉闹钟，也关掉那些“应该马上回复”的念头。读完几页书，煮了一锅番茄汤，下午的阳光刚好落在桌角。',
    contentText: '关掉闹钟，也关掉那些“应该马上回复”的念头。读完几页书，煮了一锅番茄汤，下午的阳光刚好落在桌角。',
    category: '生活',
    mood: 0.88,
    tags: ['周末', '小确幸'],
    colorValue: 0xFFF1E4B8,
  ),
  DiaryEntry(
    id: 'new-idea',
    createdAt: DateTime(2026, 9, 11, 18, 5),
    updatedAt: DateTime(2026, 9, 11, 18, 5),
    title: '一个值得试试的念头',
    content: '把想做的事情写下来，它就从模糊的愿望变成了一条可以走近的路。先从最小的一步开始。',
    contentText: '把想做的事情写下来，它就从模糊的愿望变成了一条可以走近的路。先从最小的一步开始。',
    category: '灵感',
    mood: 0.62,
    tags: ['灵感', '计划'],
    colorValue: 0xFFF2DCD2,
  ),
  DiaryEntry(
    id: 'rain',
    createdAt: DateTime(2026, 9, 8, 22, 30),
    updatedAt: DateTime(2026, 9, 8, 22, 30),
    title: '雨落下来的时候',
    content: '今天下了很久的雨。窗外的城市变得柔软，适合听一张完整的唱片，或者什么都不做。',
    contentText: '今天下了很久的雨。窗外的城市变得柔软，适合听一张完整的唱片，或者什么都不做。',
    category: '心绪',
    mood: 0.5,
    tags: ['雨天', '音乐'],
    colorValue: 0xFFE4E0ED,
  ),
];
