import { Check, Database, Keyboard, Server, Settings2, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';

export function SettingsView({ serverUrl, setServerUrl, onSave, attachmentHealth, onExportBackup, onImportBackup }) {
  const [quickCaptureStatus, setQuickCaptureStatus] = useState({ label: 'Ctrl + Shift + Space', registered: true });
  const [shortcut, setShortcut] = useState('Ctrl + Shift + Space');
  const [shortcutError, setShortcutError] = useState('');
  useEffect(() => { const result = globalThis.diaryAPI?.quickCapture?.status?.(); if (result) result.then((status) => { if (status) { setQuickCaptureStatus(status); setShortcut(status.label || shortcut); } }).catch(() => {}); }, []);
  const saveShortcut = async () => {
    const result = await globalThis.diaryAPI?.quickCapture?.setShortcut?.(shortcut);
    if (!result) return;
    setQuickCaptureStatus(result);
    if (result.label) setShortcut(result.label);
    setShortcutError(result.error || '');
  };
  const healthLabel = attachmentHealth ? `${attachmentHealth.ready} 个可用${attachmentHealth.missing ? ` · ${attachmentHealth.missing} 个缺失` : ''}${attachmentHealth.orphaned ? ` · ${attachmentHealth.orphaned} 个待清理` : ''}` : '检查中…';
  return <div className="settings-layout"><div className="settings-intro"><span className="settings-icon"><Settings2 size={19} /></span><div><p className="section-kicker">APPLICATION / SETTINGS</p><h2>设置</h2><p>桌面端的工作区、同步和记录习惯都在这里。</p></div></div><div className="settings-list"><label className="setting-row"><span className="setting-label"><Server size={17} /><span><strong>同步服务地址</strong><small>本机开发默认使用 127.0.0.1:8787</small></span></span><input className="text-input" value={serverUrl} onChange={(event) => setServerUrl(event.target.value)} /></label><div className="setting-row"><span className="setting-label"><Database size={17} /><span><strong>数据策略</strong><small>先保存到本机，再在网络可用时同步</small></span></span><span className="status-badge"><Check size={12} />离线优先</span></div><div className="setting-row"><span className="setting-label"><Database size={17} /><span><strong>附件状态</strong><small>附件复制到应用数据目录，并通过哈希记录完整性</small></span></span><span className={`status-badge ${attachmentHealth?.missing ? 'warning' : ''}`}>{attachmentHealth?.missing ? '需要检查 · ' : ''}{healthLabel}</span></div><div className="setting-row"><span className="setting-label"><Database size={17} /><span><strong>备份与恢复</strong><small>导出正文、回收站、标签、分类和附件；导入时先预览并合并</small></span></span><div className="setting-action-group"><button className="outline-button compact" type="button" onClick={onExportBackup}>导出备份</button><button className="outline-button compact" type="button" onClick={onImportBackup}>导入备份</button></div></div><div className="setting-row shortcut-setting-row"><span className="setting-label"><Sparkles size={17} /><span><strong>系统级速记</strong><small>{quickCaptureStatus.label} 唤起独立窗口，保存后恢复此前焦点</small></span></span><div className="shortcut-setting-control"><input className="text-input shortcut-input" value={shortcut} onChange={(event) => { setShortcut(event.target.value); setShortcutError(''); }} aria-label="系统级速记快捷键" /><button className="outline-button compact" type="button" onClick={saveShortcut}>应用</button>{shortcutError && <small className="setting-error">{shortcutError}</small>}</div></div><div className="setting-row"><span className="setting-label"><Keyboard size={17} /><span><strong>编辑快捷键</strong><small>Ctrl + N 新建，Ctrl + Enter 保存，Esc 关闭编辑器</small></span></span><span className="status-badge muted">已启用</span></div></div><button className="primary-button compact" onClick={onSave}>保存设置</button></div>;
}
